index:
    pattern:  /backend
    defaults: { _controller: CajaBancoBackendBundle:Page:index }    
conceptoCaja_main:
    pattern: /backend/conceptoCaja/main
    defaults: { _controller: CajaBancoBackendBundle:ConceptoCaja:main}    
conceptoCaja_insertar:
    pattern: /backend/conceptoCaja/insertar
    defaults: { _controller: CajaBancoBackendBundle:ConceptoCaja:insertar }
    requirements:
        _method:  GET|POST
        
conceptoCaja_editar:
    pattern: /backend/conceptoCaja/editar/{id}
    defaults: { _controller: CajaBancoBackendBundle:ConceptoCaja:editar }
    requirements:
        _method:  GET|POST
        
conceptoCaja_borrar:
    pattern:  /backend/conceptoCaja/borrar/{id}
    defaults: { _controller: CajaBancoBackendBundle:ConceptoCaja:borrar }         
 
conceptoCaja_listar:
    pattern: /backend/conceptoCaja/listar
    defaults: { _controller: CajaBancoBackendBundle:ConceptoCaja:listar }    
    
conceptoCaja_verTodos:
    pattern:  /backend/conceptoCaja/verTodos
    defaults: { _controller: CajaBancoBackendBundle:ConceptoCaja:verTodos } 

caja_insertar:
    pattern: /backend/caja/insertar
    defaults: { _controller: CajaBancoBackendBundle:Caja:insertar }
    requirements:
        _method:  GET|POST

caja_editar:
    pattern: /backend/caja/editar/{id}
    defaults: { _controller: CajaBancoBackendBundle:Caja:editar }
    requirements:
        _method:  GET|POST
        
caja_borrar:
    pattern:  /backend/caja/borrar/{id}
    defaults: { _controller: CajaBancoBackendBundle:Caja:borrar }         
caja_main:
    pattern:  /backend/caja/main
    defaults: { _controller: CajaBancoBackendBundle:Caja:main }  
caja_listar:
    pattern: /backend/caja/listar
    defaults: { _controller: CajaBancoBackendBundle:Caja:listar }        
caja_verTodos:
    pattern:  /backend/caja/verTodos
    defaults: { _controller: CajaBancoBackendBundle:Caja:verTodos } 
 
banco_insertar:
    pattern: /backend/banco/insertar
    defaults: { _controller: CajaBancoBackendBundle:Banco:insertar }
    requirements:
        _method:  GET|POST

banco_editar:
    pattern: /backend/banco/editar/{id}
    defaults: { _controller: CajaBancoBackendBundle:Banco:editar }
    requirements:
        _method:  GET|POST
        
banco_borrar:
    pattern:  /backend/banco/borrar/{id}
    defaults: { _controller: CajaBancoBackendBundle:Banco:borrar }         
 
banco_listar:
    pattern: /backend/banco/listar
    defaults: { _controller: CajaBancoBackendBundle:Banco:listar }    
    
banco_verTodos:
    pattern:  /backend/banco/verTodos
    defaults: { _controller: CajaBancoBackendBundle:Banco:verTodos }   

banco_main:
    pattern: /backend/banco/main
    defaults: { _controller: CajaBancoBackendBundle:Banco:main}      
ctabancaria_insertar:
    pattern: /backend/ctabancaria/insertar
    defaults: { _controller: CajaBancoBackendBundle:CuentaBancaria:insertar }
    requirements:
        _method:  GET|POST

ctabancaria_editar:
    pattern: /backend/ctabancaria/editar/{id}
    defaults: { _controller: CajaBancoBackendBundle:CuentaBancaria:editar }
    requirements:
        _method:  GET|POST
        
ctabancaria_borrar:
    pattern:  /backend/ctabancaria/borrar/{id}
    defaults: { _controller: CajaBancoBackendBundle:CuentaBancaria:borrar }         
 
ctabancaria_listar:
    pattern: /backend/ctabancaria/listar
    defaults: { _controller: CajaBancoBackendBundle:CuentaBancaria:listar }    
    
ctabancaria_verTodos:
    pattern:  /backend/ctabancaria/verTodos
    defaults: { _controller: CajaBancoBackendBundle:CuentaBancaria:verTodos }  
    
ctabancaria_main:
    pattern:  /backend/ctabancaria/main
    defaults: { _controller: CajaBancoBackendBundle:CuentaBancaria:main }      