<?php

namespace CajaBanco\BackendBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CajaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajaDetalleRepository extends EntityRepository
{
    
}