<?php

namespace CajaBanco\BackendBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaRepository extends EntityRepository
{
    public function findDescripcion($descripcion)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT c FROM CajaBancoBackendBundle:Cuenta c where c.descripcion like '$descripcion'")
            ->getResult();
    }
}